name       : gnome-user-docs
version    : '44.3'
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-user-docs/44/gnome-user-docs-44.3.tar.xz : 94e044082363438bcdbfa8549489ab6ab296a091e8b652f572133fd74db1692c
license    : CC-BY-3.0
component  : desktop.gnome.doc
summary    : GNOME core documentation
description: |
    This package contains documents which will be packaged together and shipped as gnome-user-docs in the core GNOME distribution. They should be documents targeted for end-users of GNOME and have general GNOME applicability.
builddeps  :
    - pkgconfig(yelp-xsl)
    - yelp-tools
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
