name       : gnome-user-docs
version    : 3.34.1
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-user-docs/3.34/gnome-user-docs-3.34.1.tar.xz : c2edd9d633f6f2a5fd8d5580e169d0e07de64d5d5b12a81ecbd64331d176a986
license    : CC-BY-3.0
component  : desktop.gnome.doc
summary    : GNOME core documentation
description: |
    This package contains documents which will be packaged together and
    shipped as gnome-user-docs in the core GNOME distribution. They should
    be documents targeted for end-users of GNOME and have general GNOME
    applicability.

    The GNOME Documentation Project (GDP) is responsible for this documentation
builddeps  :
    - pkgconfig(yelp-xsl)
    - yelp-tools
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
