name       : gnome-user-docs
version    : 3.38.2
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-user-docs/3.38/gnome-user-docs-3.38.2.tar.xz : f50cbb3a39dd6290c82f9476159606751ec9f25baafafb4c7c95b10f90f534c1
license    : CC-BY-3.0
component  : desktop.gnome.doc
summary    : GNOME core documentation
description: |
    This package contains documents which will be packaged together and shipped as gnome-user-docs in the core GNOME distribution. They should be documents targeted for end-users of GNOME and have general GNOME applicability.
builddeps  :
    - pkgconfig(yelp-xsl)
    - yelp-tools
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
