name       : gnome-user-docs
version    : 3.28.1
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-user-docs/3.28/gnome-user-docs-3.28.1.tar.xz : d0ed86816736c59edcf974f9cdebee61bc8edb9add26597ac9d2b0211a3a32a1
license    : CC-BY-3.0
component  : desktop.gnome.doc
summary    : GNOME core documentation
description: |
    This package contains documents which will be packaged together and
    shipped as gnome-user-docs in the core GNOME distribution. They should
    be documents targeted for end-users of GNOME and have general GNOME
    applicability.

    The GNOME Documentation Project (GDP) is responsible for this documentation
builddeps  :
    - pkgconfig(yelp-xsl)
    - yelp-tools
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
